#!/usr/bin/env python

# please consider uploading the link to imgur before
handy_links = {
    'haters'     : 'http://i.imgur.com/DmgKb.jpg',
    'haterz'     : 'http://i.imgur.com/LGOwa.gif',
    'palomitas'  : 'http://i.imgur.com/M33BF.gif',
    'pics'       : 'http://i.imgur.com/UdXdM.jpg',
    'megusta'    : 'http://i.imgur.com/ibzJX.jpg',
    'yaoming'    : 'http://i.imgur.com/AwWvY.png',
    'trollface'  : 'http://i.imgur.com/Njy8l.png',
    'sfuck'      : 'http://i.imgur.com/sXtZc.jpg',
    'goback'     : 'http://i.imgur.com/pLQUU.gif',
    'dealwithit' : 'http://i.imgur.com/G7f9J.gif',
    'likeigive'  : 'http://i.imgur.com/6kO74.gif',
    'mindblown'  : 'http://i.imgur.com/fbelJ.gif',
    'clap'       : 'http://i.imgur.com/1WypN.gif',
    'truestory'  : 'http://i.imgur.com/51Ekh.png',
    'laugh'      : 'http://i.imgur.com/JFbhu.gif',
    'rolleyes'   : 'http://i.imgur.com/RqtZe.gif',
    'fuckthis'   : 'http://i.imgur.com/Bsfnw.gif',
    'lol'        : 'http://i.imgur.com/LFguu.gif',
    'wrong'      : 'http://i.imgur.com/TBL3j.gif',
    'coolstory'  : 'http://i.imgur.com/iVLKt.gif',
    'f7u12'      : 'http://i.imgur.com/U8jcB.gif',
    'facepalm'   : 'http://i.imgur.com/6eKQz.gif',
    'party'      : 'http://i.imgur.com/yq9A0.gif',
    'rickroll'   : 'http://i.imgur.com/UR1x2.gif',
    'punch'      : 'http://i.imgur.com/dEhlI.gif',
    'orly'       : 'http://i.imgur.com/HX9Tt.gif',
    'wtf'        : 'http://i.imgur.com/ZlC7s.gif',
    'onoudidnt'  : 'http://i.imgur.com/1mUDX.gif',
    'challenge'  : 'http://i.imgur.com/02HJ9.png',
    'shark'      : 'http://i.imgur.com/7fsza.png',
    'trap'       : 'http://i.imgur.com/NcCIw.jpg',
    'notsure'    : 'http://i.imgur.com/WH4mO.gif',
    'rolfmao'    : 'http://i.imgur.com/VlOTd.gif',
    'orly'       : 'http://i.imgur.com/wdlmj.gif',
    'cry'        : 'http://i.imgur.com/SlOFG.gif',
    'disapprove' : 'http://i.imgur.com/3QAmc.gif',
    'tldr'       : 'http://i.imgur.com/mOH78.gif',
    'disgonbgud' : 'http://i.imgur.com/sbk60.gif',
    'rushitting' : 'http://i.imgur.com/8MwwZ.gif'
}
